# Render configuration file
# See https://render.com/docs/deploy-render-yaml for more details

services:
  - type: web
    name: jace-farms-client
    env: static
    buildCommand: |
      cd client && \
      npm install && \
      npm run build
    staticPublishPath: "./client/dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: jace-farms-api
    env: node
    buildCommand: |
      cd server && \
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: jace-farms-db
          property: connectionString
    plan: free
    autoDeploy: true
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false

# Uncomment and configure if you're using a database
# databases:
#   - name: jace-farms-db
#     databaseName: jacefarms
#     user: jacefarms
#     plan: free
