# Render configuration for Jace Farms
# Fullstack Node.js + Vite deployment
# See https://render.com/docs/deploy-render-yaml

services:
  - type: web
    name: jace-farms
    env: node
    buildCommand: |
      npm install && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    plan: free
    autoDeploy: true
    region: oregon

# Uncomment and configure if using a Render-managed database
# databases:
#   - name: jace-farms-db
#     databaseName: jacefarms
#     user: jacefarms
#     plan: free
