services:
  - type: web
    name: jace-farms
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm install -g vite
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    plan: free
    autoDeploy: true
    region: oregon
