services:
  - type: web
    name: jace-farms
    env: node
    buildCommand: |
      # Install root dependencies
      npm install
      
      # Install client dependencies and build
      cd client
      npm install
      
      # Use npx to run Vite directly without global install
      npx vite build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    plan: free
    autoDeploy: true
    region: oregon
